## Worksheet 2

Welcome to worksheet 2! This worksheet was designed to allow you to practice what was covered in the assigned readings & lectures/videos/recordings. The labs problems will be more challenging then those in the worksheet, and the worksheet questions will help prepare you for them. Time will be provided to work on the worksheets in small groups during lecture, however it is not expected that you will complete the worksheet in this time. You are expected to spend some indpendent time working on the worksheet after lecture. 

**Worksheets are due on Saturdays at 6 pm, and must be submitted as `.ipynb` file OR the `zip` file generated at the last step (under Submission heading) in this worksheet/lab to Gradescope.**

### Getting your homework (i.e., worksheet and lab repositories) from GitHub.ubc.ca onto your computer:

Watch the video titled "Downloading the lab assignment from GitHub to JupyterLab" from DSCI 521, accessible [here](https://pages.github.ubc.ca/MDS-2022-23/DSCI_521_platforms-dsci_students/materials/appendices/submit-assignment.html).

### Worksheet mechanics

- **There is autograding in this lab, so please do not move or rename this file. Also, do not copy and paste cells, if you need to add new cells, create new cells via the "Insert a cell below" button instead.**

Run the cell below to load the libraries needed for this worksheet, and to check your answers as you go!

In [63]:
library(testthat)
library(digest)
options(repr.matrix.max.rows = 10)

## 1. The operators and key datatypes for Data Science in R

### Exercise 1
rubric={autograde:1}

In R, all elements of vectors and lists must have the same type. True or false?

Create an object with a valid logical value corresponding to whether you believe the answer to the question above is `TRUE` or `FALSE`. Bind the name `answer1` to this object.

In [64]:
answer1 <- NULL
# BEGIN SOLUTION NO PROMPT
answer1 <- FALSE
# END SOLUTION

answer1

[1] FALSE

In [65]:
# TESTS
expect_true(is.logical(answer1))
expect_equal(digest(answer1 + 13), '709a7faa72cb6f3be79d683e234ccb25')

### Exercise 2
rubric={autograde:1}

Create a vector containing the names of the types of the four most common types of vectors. Bind the name `answer2` to this object.

In [66]:
answer2 <- NULL
# BEGIN SOLUTION NO PROMPT
answer2 <- c("character", "double", "integer", "logical")
# END SOLUTION

answer2

[1] "character" "double"    "integer"   "logical"

In [67]:
# TESTS
expect_true(is.character(answer2))
expect_equal(length(answer2), 4)
expect_equal(digest(paste(tolower(sort(answer2)), collapse="")), 'c74b4d11b8d68d188749e3a83e1266c8')

### Exercise 3
rubric={autograde:1}

What type are the following mixed vectors coerced to? 

<img src="img/vec_a-c.png" width=600 align="left">

To answer this question make three objects, each containing the character value for the name of the type the vector is coherced to. Bind the names `vect_a_type`, `vec_b_type` and `vec_c_type` to these objects.

In [68]:
vect_a_type <- NULL
vect_b_type <- NULL
vect_c_type <- NULL
# BEGIN SOLUTION NO PROMPT
vect_a_type <- 'double'
vect_b_type <- 'character'
vect_c_type <- 'character'
# END SOLUTION

vect_a_type
vect_b_type
vect_c_type

[1] "double"

[1] "character"

[1] "character"

In [69]:
# TESTS
expect_true(is.character(vect_a_type))
expect_equal(length(vect_a_type), 1)
expect_true(is.character(vect_b_type))
expect_equal(length(vect_b_type), 1)
expect_true(is.character(vect_c_type))
expect_equal(length(vect_c_type), 1)
expect_equal(digest(vect_a_type), '8fafbeb771f728e2d591608d61232af5')
expect_equal(digest(vect_b_type), 'af31d61b8795057ce1ce2e040685107c')
expect_equal(digest(vect_c_type), 'af31d61b8795057ce1ce2e040685107c')

### Exercise 4
rubric={autograde:1}

Create vector containing the following values: 2.2, 15.0,  3.5, 4.0, 30.0 (in the order we list them) and bind the name `values` to it. *__Hint__: The columns function, `c()`, is helpful for constructing vectors.*

In [70]:
values <- NULL
# BEGIN SOLUTION NO PROMPT
values <- c(2.2, 15, 3.5, 4, 30)
# END SOLUTION

values

[1]  2.2 15.0  3.5  4.0 30.0

In [71]:
# TESTS
expect_true(is.numeric(values))
expect_equal(length(values), 5)
expect_false(is.list(values))
expect_equal(round(sum(values)), 55)

### Exercise 5
rubric={autograde:1}

Use the `[` syntax to get the first element from the vector `values` and bind the name `values_first` to it.

In [72]:
values_first <- NULL
# BEGIN SOLUTION NO PROMPT
values_first <- values[1]
# END SOLUTION

values_first

[1] 2.2

In [73]:
# TESTS
expect_true(is.numeric(values_first))
expect_equal(length(values_first), 1)
expect_false(is.list(values_first))
expect_equal(round(sum(values_first)), 2)

### Exercise 6
rubric={autograde:1}

Use the `[` syntax  to get the last element from the vector `values`. Bind the name `values_last` to the vector containing the last element from values.

*hint: use `length()` to find the length of a 1-D collection (e.g., list, variable)*

In [74]:
values_last <- NULL
# BEGIN SOLUTION NO PROMPT
values_last <- values[length(values)]
# END SOLUTION

values_last

[1] 30

In [75]:
# TESTS
expect_true(is.numeric(values_last))
expect_equal(length(values_last), 1)
expect_false(is.list(values_last))
expect_equal(round(sum(values_last)), 30)

### Exercise 7
rubric={autograde:1}

There was a mistake in the data entry process, and the value for the second element in the vector should be 3.14159. Modify the copy of `values` that we provide (`values_updated`) below to change the second entry to 3.14159. Do not use `c()` to create a new vector from scratch.

In [76]:
values_updated <- values

# YOUR CODE HERE
# BEGIN SOLUTION NO PROMPT
values_updated[2] <- 3.14159
# END SOLUTION

values_updated

[1]  2.20000  3.14159  3.50000  4.00000 30.00000

In [77]:
# TESTS
expect_true(is.numeric(values_updated))
expect_equal(length(values_updated), 5)
expect_false(is.list(values_updated))
expect_equal(round(sum(values_updated)), 43)

### Exercise 8
rubric={autograde:1}

Create a list (not a vector) with the **original** values contained in the `values` vector you just explored ( 2.2, 15.0, 3.5, 4.0,  and 30.0). Bind the name `value_list` to the list you create.

*Hint: use the `list` function to create a list in R.*

In [78]:
value_list <- NULL
# BEGIN SOLUTION NO PROMPT
value_list <- list(2.2, 15, 3.5, 4, 30)
# END SOLUTION

value_list

[[1]]
[1] 2.2

[[2]]
[1] 15

[[3]]
[1] 3.5

[[4]]
[1] 4

[[5]]
[1] 30

In [79]:
# TESTS
expect_true(is.numeric(value_list[[1]]))
expect_true(is.numeric(value_list[[2]]))
expect_true(is.numeric(value_list[[3]]))
expect_true(is.numeric(value_list[[4]]))
expect_true(is.numeric(value_list[[5]]))
expect_equal(length(value_list), 5)
expect_true(is.list(value_list))
expect_equal(round(Reduce(`+`, value_list)), 55)

### Exercise 9
rubric={autograde:1}


Get the first element from the list and bind the name `value_list_first` to it. Ensure that what you return is a number (**not a list itself**). Remember: When indexing, using `[` gives you the same type of object as the object being indexed (e.g., returns a list when applied to a list), whereas `[[` removes one level of structure (e.g., if the object is a list of numbers, you get the number back itself).

In [80]:
value_list_first <- NULL
# BEGIN SOLUTION NO PROMPT
value_list_first <- value_list[[1]]
# END SOLUTION

value_list_first

[1] 2.2

In [81]:
# TESTS
expect_true(is.numeric(value_list_first))
expect_equal(length(value_list_first), 1)
expect_false(is.list(value_list_first))
expect_equal(round(sum(value_list_first)), 2)

### Exercise 10
rubric={autograde:1}

Consider the built-in/base R `faithful` data frame shown below, which contains data of the waiting time between eruptions and the duration of the eruptions for the Old Faithful geyser in Yellowstone National Park, Wyoming, USA. Use the `$` syntax to get a vector of the waiting times between eruptions. Bind the name `waiting_time` to the vector.

In [82]:
# comment this cell out if you don't have the IRdisplay package installed
# and you don't want install it
# you can instead visit the video link directly here: https://youtu.be/UXFEiEMvdDo
library(IRdisplay)
display_html('<iframe width="560" height="315" src="https://www.youtube.com/embed/UXFEiEMvdDo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>')

In [83]:
faithful

eruptions waiting
1   3.600     79     
2   1.800     54     
3   3.333     74     
4   2.283     62     
5   4.533     85     
⋮   ⋮         ⋮      
268 4.117     81     
269 2.150     46     
270 4.417     90     
271 1.817     46     
272 4.467     74

In [84]:
waiting_time <- NULL
# BEGIN SOLUTION NO PROMPT
waiting_time <- faithful$waiting
# END SOLUTION

waiting_time

[1] 79 54 74 62 85 55 88 85 51 85 54 84 78 47 83 52 62 84 52 79 51 47 78 69 74
 [26] 83 55 76 78 79 73 77 66 80 74 52 48 80 59 90 80 58 84 58 73 83 64 53 82 59
 [51] 75 90 54 80 54 83 71 64 77 81 59 84 48 82 60 92 78 78 65 73 82 56 79 71 62
 [76] 76 60 78 76 83 75 82 70 65 73 88 76 80 48 86 60 90 50 78 63 72 84 75 51 82
[101] 62 88 49 83 81 47 84 52 86 81 75 59 89 79 59 81 50 85 59 87 53 69 77 56 88
[126] 81 45 82 55 90 45 83 56 89 46 82 51 86 53 79 81 60 82 77 76 59 80 49 96 53
[151] 77 77 65 81 71 70 81 93 53 89 45 86 58 78 66 76 63 88 52 93 49 57 77 68 81
[176] 81 73 50 85 74 55 77 83 83 51 78 84 46 83 55 81 57 76 84 77 81 87 77 51 78
[201] 60 82 91 53 78 46 77 84 49 83 71 80 49 75 64 76 53 94 55 76 50 82 54 75 78
[226] 79 78 78 70 79 70 54 86 50 90 54 54 77 79 64 75 47 86 63 85 82 57 82 67 74
[251] 54 83 73 73 88 80 71 83 56 79 78 84 58 83 43 60 75 81 46 90 46 74

In [85]:
# TESTS
expect_true(is.numeric(waiting_time))
expect_equal(length(waiting_time), 272)
expect_false(is.list(waiting_time))
expect_equal(round(sum(waiting_time)), 19284)

### Exercise 11
rubric={autograde:1}

Consider the built-in/base R `CO2` data frame shown below, which contains data from an experiment on carbon dioxide uptake in the grass plant *Echinochloa crus-galli*. Use the `[` syntax to extract rows 1 - 5, and only the columns `conc` and `uptake`. Bind the name `first_five_measurements` to this smaller data frame.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Echinochloa_crus-galli01.jpg/440px-Echinochloa_crus-galli01.jpg" width=200>

*Source: https://en.wikipedia.org/wiki/Echinochloa_crus-galli*

In [86]:
CO2

Plant Type        Treatment  conc uptake
1  Qn1   Quebec      nonchilled  95  16.0  
2  Qn1   Quebec      nonchilled 175  30.4  
3  Qn1   Quebec      nonchilled 250  34.8  
4  Qn1   Quebec      nonchilled 350  37.2  
5  Qn1   Quebec      nonchilled 500  35.3  
⋮  ⋮     ⋮           ⋮          ⋮    ⋮     
80 Mc3   Mississippi chilled     250 17.9  
81 Mc3   Mississippi chilled     350 17.9  
82 Mc3   Mississippi chilled     500 17.9  
83 Mc3   Mississippi chilled     675 18.9  
84 Mc3   Mississippi chilled    1000 19.9

In [87]:
first_five_measurements <- NULL
# BEGIN SOLUTION NO PROMPT
first_five_measurements <- CO2[1:5, 4:5]
# END SOLUTION

first_five_measurements

conc uptake
1  95  16.0  
2 175  30.4  
3 250  34.8  
4 350  37.2  
5 500  35.3

In [88]:
# TESTS
expect_true(is.data.frame(first_five_measurements))
expect_equal(nrow(first_five_measurements), 5)
expect_equal(ncol(first_five_measurements), 2)
expect_true(c("conc") %in% colnames(first_five_measurements))
expect_true(c("uptake") %in% colnames(first_five_measurements))
expect_equal(length(colnames(first_five_measurements)), 2)
expect_equal(round(sum(first_five_measurements$conc)), 1370)

Congratulations! You are done the worksheet!!! Pat yourself on the back, and submit your worksheet to Gradescope!