name: lab1
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - nb_conda_kernels
    - r-base=4.1.1 
    - r-essentials 
    - r-devtools
    - libgit2
    - pip:
        - -r requirements.txt